Blog9to5/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                     .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    photo = models.ImageField(upload_to='blog_photos', null=True)
    objects = models.Manager()
    published = PublishedManager()
        
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

Blog9to5/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
 
# Views
@login_required
def home(request):
    return render(request, "registration/success.html", {})
 
def register(request):
    if request.method == 'POST':
        print('get reg req')
        form = UserCreationForm(request.POST)
        print(form.fields)
        if form.is_valid():
            print('form is valid!')
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('login')
        else:
            print('form is not valid')
            print(form.errors)
            return redirect('/')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post

# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request,
                 'blog/post/list.html',
                 {'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post,
                             id=id,
                             status=Post.Status.PUBLISHED)
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="{% static "css/style.css" %}" rel="stylesheet">
  
  {% comment %} <script src="{% static 'js/script.js' %}"></script>    {% endcomment %}
  <base href="{% static '/' %}">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark px-0 py-3 mb-5" style="background-color: #16192c">
    <div class="container-xl">
      <!-- Logo -->
      <a class="navbar-brand" href="/">
        <img src="{% static 'FutureWatch-1.png' %}" class="h-8" alt="9to5ml" height="54">
      </a>
      <!-- Navbar toggle -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- Nav -->
        <div class="navbar-nav mx-lg-auto">
          <a class="nav-item nav-link active" href="#" aria-current="page">Home</a>
          <a class="nav-item nav-link" href="#">About</a>
          <a class="nav-item nav-link" href="#">Contact</a>
        </div>
        <!-- Right navigation -->
        {% if not user.is_authenticated %}
        <div class="navbar-nav ms-lg-4">
          <a class="nav-item nav-link" href="/login">Login/Register</a>
        </div>
        <!-- Action -->
        {% comment %} <div class="d-flex align-items-lg-center mt-3 mt-lg-0">
          <a href="/register" class="btn btn-sm btn-primary w-full w-lg-auto">
            Register
          </a>
        </div> {% endcomment %}
        {% elif user.is_authenticated  %}
        <div class="navbar-nav ms-lg-4">
          <a class="nav-item nav-link" href="/logout">Logout</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>


      {% block content %}
      {% endblock %}

</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="preview-card ">
      <h1>{{ post.title }}</h1>
      <p class="date">
        <b>Published: </b> {{ post.publish|date }} by {{ post.author }}
      </p>
      <div class="post-text">
        {{ post.body|linebreaks }}
      </div>
      
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<div class="container">
  <div class="row mt-5">
    {% for post in posts %}
    <div class="preview-card">
      <div class="preview-card__wrp">
        <div class="preview-card__item">
          <div class="preview-card__img">
            <img src="{{post.photo.url}}" alt="">
          </div>
          <div class="preview-card__content">
            <span class="preview-card__code">{{ post.publish }}</span>
            <div class="preview-card__title">{{ post.title }}</div>
            <div class="preview-card__text">{{ post.body|truncatewords:15|linebreaks }} </div>
            <a href="{% url 'blog:post_detail' post.id %}" class="preview-card__button">READ Now</a>
          </div>
        </div>

      </div>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}